achat_martin = {"HARVEYS":"m",
                "JUMBO RESTAURANT":"m",
                "VIRGIN MOBILE":"m",
                "ULTRAMAR":"m",
                "SUBWAY":"m",
                "MCDONALD":"m",
                "DOMINOS":"m",
                "CHEZ GERARD":"m",
                "AU COQ":"m",
                "SCORES":"m",
                "BARBIES":"m",
                "SHELL":"m",
                "RTM - ABONNEMENT":"m",
                "A&W":"m",
                "PACINI":"m",
                'LES DELICES':"m",
                "NICKELS":"m",
                "PETRO":"m",
                "WENDY":"m",
                "JULIANO":"m",
                "MEGAPLEX":"m",
                "AMIR":"m",
                "MIKE'S":"m",
                "STATIONNEMENT":"m",
                "IGA":"c",
                "METRO":"c",
                "BELL CANADA":"c",
                "RENO DEPOT":"c",
                "RONA":"c",
                "NETFLIX.COM":"c",
                "LE LUNCH":"c",
                "MICROSOFT":"c",
                "HOME DEPOT":"c",
                "SEPAQ":"c",
                "COSTCO":"c",
                "SAQ":"c",
                }

achat_anne_marie = {"HARVEYS":"a",
                "JUMBO RESTAURANT":"a",
                "VIRGIN MOBILE":"a",
                "ULTRAMAR":"a",
                "SUBWAY":"a",
                "MCDONALD":"a",
                "DOMINOS":"a",
                "CHEZ GERARD":"a",
                "AU COQ":"a",
                "SCORES":"a",
                "BARBIES":"a",
                "SHELL":"a",
                "RTM - ABONNEMENT":"a",
                "A&W":"a",
                "PACINI":"a",
                'LES DELICES':"a",
                "NICKELS":"a",
                "PETRO":"a",
                "WENDY":"a",
                "JULIANO":"a",
                "MEGAPLEX":"a",
                "AMIR":"a",
                "MIKE'S":"a",
                "STATIONNEMENT":"a",
                "BAILA":"a",
                "MARCHE DORION":"a",
                "PANDORA":"a",
                "IGA":"c",
                "METRO":"c",
                "BELL CANADA":"c",
                "RENO DEPOT":"c",
                "RONA":"c",
                "NETFLIX.COM":"c",
                "LE LUNCH":"c",
                "MICROSOFT":"c",
                "HOME DEPOT":"c",
                "SEPAQ":"c",
                "COSTCO":"c",

                }